files:
  species_file: CBSQB3_2019.10.25.txt # Molecular database
  res_file: C:\Users\THINKPAD P16S\.gemini\antigravity-ide\scratch\RGA_repo\output\lam_CBSQB3.out #res_test_2.out
  executor: Lam # Name of who runs the code
  species_smiles: "C1CC2=CC=CC=C2C1" # CC1COC(O1)=O SMILES wrapped by quotes, multiple species split by space/tab
  calc_value: 17.3 # Calculated value (kcal/mol), no quote needed, same as smiles
  
rxn_constraints:
  no_of_cores: 6
  same_coef: true
  no_species: 4
  complete_set: true
  stochastic: false
  no_trials: 100000
  seed: 42 # Empty or integer value, used for reproducibility of the stochastic approach
  # Atom constraints
  lone_electron: false
  electron_pair: true
  electron_pair_type: false
  atom_with_hydro: false
  atom_hybridization: false
  atom_hybrid_with_hydro: false
  atom_degree: false
  atom_type: C
  radical: false
  
  # Bond constraints
  bond_type:
    hydro_bond: true
    normal_bond: false
    bond_hybridization: false
    bond_with_hydro: false
    bond_degree: false
    bond_radical: false
    bond_atom_type: C 
    ring: false
    
similarity:
  similarity_on: true
  radius: 4
  chirality: true
  feature_method: HRCF # HRCF, ECFP, FCFP, BoB, CM, AP, TT
  
analysis:
  analysis_on: true
  filter: true
  top: 0.1